language: php
php: 7.2
before_install:
  - composer self-update --2
  - composer config repositories.packagist.com composer https://repo.packagist.com/idhl/snowio/
  - if [[ -n $PACKAGIST_TOKEN ]]; then composer config http-basic.repo.packagist.com token $PACKAGIST_TOKEN; fi
cache:
  directories: $HOME/.composer/cache
before_script: composer install --no-interaction
script: vendor/bin/phpunit --coverage-clover=coverage.xml
after_success: bash <(curl -s https://codecov.io/bash)
